"""Initial migration

Revision ID: b545057304d5
Revises: 
Create Date: 2025-11-12 20:20:57.076784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b545057304d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitrix_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mode', sa.Enum('STUB', 'LIVE', name='bitrixmode'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitrix_call_logs_id'), 'bitrix_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_bitrix_call_logs_mode'), 'bitrix_call_logs', ['mode'], unique=False)
    op.create_index(op.f('ix_bitrix_call_logs_timestamp'), 'bitrix_call_logs', ['timestamp'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('cron_or_rrule', sa.String(length=255), nullable=False),
    sa.Column('assigned_user_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('auto_replace_on_absence', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_enabled'), 'schedules', ['enabled'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_name'), 'schedules', ['name'], unique=False)
    op.create_index(op.f('ix_schedules_template_id'), 'schedules', ['template_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event', sa.Enum('CHECK_CREATED', 'CHECK_COMPLETED', 'REPORT_READY', 'TASK_CREATED', name='webhookevent'), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_active'), 'webhook_subscriptions', ['active'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_event'), 'webhook_subscriptions', ['event'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_id'), 'webhook_subscriptions', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('checklist_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='templatestatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_templates_id'), 'checklist_templates', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_templates_name'), 'checklist_templates', ['name'], unique=False)
    op.create_index(op.f('ix_checklist_templates_status'), 'checklist_templates', ['status'], unique=False)
    op.create_table('user_role_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('check_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspector_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='checkstatus'), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_instances_department_id'), 'check_instances', ['department_id'], unique=False)
    op.create_index(op.f('ix_check_instances_id'), 'check_instances', ['id'], unique=False)
    op.create_index(op.f('ix_check_instances_inspector_id'), 'check_instances', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_check_instances_project_id'), 'check_instances', ['project_id'], unique=False)
    op.create_index(op.f('ix_check_instances_status'), 'check_instances', ['status'], unique=False)
    op.create_index(op.f('ix_check_instances_template_id'), 'check_instances', ['template_id'], unique=False)
    op.create_table('checklist_template_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_template_versions_id'), 'checklist_template_versions', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_template_versions_template_id'), 'checklist_template_versions', ['template_id'], unique=False)
    op.create_index(op.f('ix_checklist_template_versions_version'), 'checklist_template_versions', ['version'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('check_instance_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'HTML', 'JSON', name='reportformat'), nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'READY', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['check_instance_id'], ['check_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_check_instance_id'), 'reports', ['check_instance_id'], unique=False)
    op.create_index(op.f('ix_reports_format'), 'reports', ['format'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('task_local',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bitrix_id', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_local_bitrix_id'), 'task_local', ['bitrix_id'], unique=False)
    op.create_index(op.f('ix_task_local_id'), 'task_local', ['id'], unique=False)
    op.create_index(op.f('ix_task_local_report_id'), 'task_local', ['report_id'], unique=False)
    op.create_index(op.f('ix_task_local_status'), 'task_local', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_local_status'), table_name='task_local')
    op.drop_index(op.f('ix_task_local_report_id'), table_name='task_local')
    op.drop_index(op.f('ix_task_local_id'), table_name='task_local')
    op.drop_index(op.f('ix_task_local_bitrix_id'), table_name='task_local')
    op.drop_table('task_local')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_format'), table_name='reports')
    op.drop_index(op.f('ix_reports_check_instance_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_checklist_template_versions_version'), table_name='checklist_template_versions')
    op.drop_index(op.f('ix_checklist_template_versions_template_id'), table_name='checklist_template_versions')
    op.drop_index(op.f('ix_checklist_template_versions_id'), table_name='checklist_template_versions')
    op.drop_table('checklist_template_versions')
    op.drop_index(op.f('ix_check_instances_template_id'), table_name='check_instances')
    op.drop_index(op.f('ix_check_instances_status'), table_name='check_instances')
    op.drop_index(op.f('ix_check_instances_project_id'), table_name='check_instances')
    op.drop_index(op.f('ix_check_instances_inspector_id'), table_name='check_instances')
    op.drop_index(op.f('ix_check_instances_id'), table_name='check_instances')
    op.drop_index(op.f('ix_check_instances_department_id'), table_name='check_instances')
    op.drop_table('check_instances')
    op.drop_table('user_role_association')
    op.drop_index(op.f('ix_checklist_templates_status'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_name'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_id'), table_name='checklist_templates')
    op.drop_table('checklist_templates')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_webhook_subscriptions_id'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_event'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_active'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schedules_template_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_name'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_enabled'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_bitrix_call_logs_timestamp'), table_name='bitrix_call_logs')
    op.drop_index(op.f('ix_bitrix_call_logs_mode'), table_name='bitrix_call_logs')
    op.drop_index(op.f('ix_bitrix_call_logs_id'), table_name='bitrix_call_logs')
    op.drop_table('bitrix_call_logs')
    # ### end Alembic commands ###

